export const previews = [
  { title: 'Тенерифе', url: '/img/charter/location/location1.png' },
  { title: 'Италия', url: '/img/charter/location/location2.png' },
  { title: 'Карибы', url: '/img/charter/location/location3.png' },
  { title: 'Хорватия', url: '/img/charter/location/location4.png' },
  { title: 'Испания', url: '/img/charter/location/location5.png' },
]

export const locations = [
  {
    title: 'Средиземноморье',
    countries: [
      {
        title: 'Испания',
        regions: [
          { title: 'Ибица' },
          { title: 'Майорка' },
          { title: 'Барселона' },
          { title: 'Каталония' },
          { title: 'Канарские острова / Канары' },
          { title: 'Тенерифе' },
          { title: 'Балеарские острова' },
          { title: 'Аликанте' },
        ],
      },
      { title: 'Монако', regions: [{ title: 'Монте-Карло' }] },
      { title: 'Средиземное море' },
      { title: 'Хорватия' },
      {
        title: 'Италия',
        regions: [
          { title: 'Сардиния', isFavorite: true },
          { title: 'Палермо' },
          { title: 'Тоскана' },
          { title: 'Лигурия' },
          { title: 'Сицилия' },
          { title: 'Амальфи' },
          { title: 'Портофино' },
          { title: 'Неаполь' },
        ],
      },
      { title: 'Черногория', regions: [{ title: 'Тиват' }] },
      { title: 'Кипр' },
      { title: 'Португалия' },
      {
        title: 'Франция',
        regions: [
          { title: 'Канны' },
          { title: 'Корсика' },
          { title: 'Лазурный берег' },
          { title: 'Марсель' },
          { title: 'Ницца' },
          { title: 'Сен-Тропе' },
          { title: 'Прованс' },
        ],
      },
      { title: 'Мальта' },
      { title: 'Адриатика' },
      { title: 'Словения' },
      { title: 'Венеция' },
      { title: 'Албания' },
      {
        title: 'Греция',
        regions: [
          { title: 'Халкидики' },
          { title: 'Афины' },
          { title: 'Корфу' },
          { title: 'Родос' },
          { title: 'Санторини' },
          { title: 'Корфу' },
        ],
      },
      {
        title: 'Турция',
        regions: [
          { title: 'Мармарис' },
          { title: 'Гечек' },
          { title: 'Бодрум' },
        ],
      },
    ],
  },
  {
    title: 'Европа',
    countries: [
      { title: 'Великобритания' },
      { title: 'Ирландия' },
      { title: 'Нидерланды' },
      { title: 'Прибалтика' },
      { title: 'Ислания' },
      { title: 'Дания' },
      { title: 'Норвегия', regions: [{ title: 'Шпицберген' }] },
      { title: 'Швеция' },
      { title: 'Гренландия' },
      { title: 'Финляндия' },
      {
        title: 'Россия',
        regions: [
          { title: 'Москва' },
          { title: 'Сочи' },
          { title: 'Санкт-Петербург' },
        ],
      },
      { title: 'Арктика' },
      { title: 'Скандинавия' },
    ],
  },
  {
    title: 'Карибы',
    countries: [
      { title: 'Виргинские острова' },
      { title: 'Наветренные острова' },
      { title: 'Подветренные острова' },
      { title: 'Доминикана' },
      { title: 'Тринидад и Тобаго' },
      { title: 'Куба' },
      { title: 'Бермуды' },
      { title: 'Багамы' },
      { title: 'Гренадины' },
    ],
  },
  {
    title: 'Америка',
    countries: [
      { title: 'Канада' },
      { title: 'Мексика' },
      { title: 'Флорида' },
      { title: 'Новая Англия' },
      { title: 'Калифорния' },
      { title: 'Гаваи' },
      { title: 'Аляска' },
      { title: 'Великие озера' },
      { title: 'Панама' },
      { title: 'Белиз' },
      { title: 'Коста-Рика' },
      { title: 'Гондурас' },
      { title: 'Никарагуа' },
      { title: 'Бразилия' },
      { title: 'Аргентина' },
      { title: 'Колумбия' },
      { title: 'Уругвай' },
      { title: 'Чили' },
      { title: 'Галапагосские острова' },
      { title: 'Патагония' },
      { title: 'Антарктика' },
      { title: 'Перу' },
      { title: 'Майами' },
    ],
  },
  {
    title: 'Азия',
    countries: [
      { title: 'Тайланд', regions: [{ title: 'Пхукет' }] },
      { title: 'Малайзия' },
      { title: 'Сингапур' },
      { title: 'Индонезия', regions: [{ title: 'Бали' }, { title: 'Комодо' }] },

      { title: 'Вьетнам' },
      { title: 'Гонконг' },
      { title: 'Тайвань' },
      { title: 'Филиппины' },
      { title: 'Мьянма' },
      { title: 'Япония' },
    ],
  },
  {
    title: 'Индийский океан',
    countries: [
      { title: 'Мальдивы' },
      { title: 'Сейшелы' },
      { title: 'Маврикий' },
      { title: 'Мадагаскар' },
      { title: 'Реюньон' },
    ],
  },
  {
    title: 'Тихий океан',
    countries: [
      { title: 'Фиджи' },
      { title: 'Вануату' },
      { title: 'Тонга' },
      { title: 'Новая Каледония' },
      { title: 'Папуа-Новая Гвинея' },
      { title: 'Палау' },
      { title: 'Соломоновы острова' },
      { title: 'Французская Полинезия' },
      { title: 'Австралия' },
      { title: 'Большой Барьерный риф' },
      { title: 'Новая Зеландия' },
      { title: 'Таити' },
    ],
  },
  {
    title: 'Ближний восток',
    countries: [
      { title: 'ОАЭ', regions: [{ title: 'Дубай' }, { title: 'Абу-Даби' }] },
      { title: 'Красное море' },
      { title: 'Арабский залив' },
      { title: 'Абу-Даби' },
      { title: 'Египет' },
      { title: 'Дубаи' },
    ],
  },
]
