export const FavoritesData = {
  header: `Избранное`,
  sorts: ['популярное', 'по цене', 'по длине', 'по состоянию'],
  sortsMobile: [
    { title: 'популярное', mobileTitle: 'Популярное' },
    {
      mobileTitle: 'По цене (дорогие — дешевые)',
      title: 'по цене',
      sort: 'desc',
    },
    {
      mobileTitle: 'По цене (дешевые — дорогие)',
      title: 'по цене',
      sort: 'asc',
    },
    {
      mobileTitle: 'По длине (длинные — короткие)',
      title: 'по длине',
      sort: 'desc',
    },
    {
      mobileTitle: 'По длине (короткие — длинные)',
      title: 'по длине',
      sort: 'asc',
    },
    {
      mobileTitle: 'По состоянию (новые — б/у)',
      title: 'по состоянию',
      sort: 'desc',
    },
    {
      mobileTitle: 'По состоянию (б/у — новые)',
      title: 'по состоянию',
      sort: 'asc',
    },
  ],
  currencies: ['€', '$', '£', '₽'],
  favoritesList: [
    {
      title: `Heesen 55M FDHF Pollux`,
      buildDate: 2020,
      length: 55,
      cabins: 6,
      images: [
        '/img/yacht/favorites/yacht1.jpg',
        '/img/yacht/favorites/yacht2.jpg',
        '/img/yacht/favorites/yacht3.jpg',
        '/img/yacht/favorites/yacht4.jpg',
        '/img/yacht/favorites/yacht5.jpg',
      ],
      price: '43 000 000 €',
      condition: `Новая`,
      alt: `Heesen 55M FDHF Pollux`,
      badge: `Эксклюзив`,
      isFavorite: true,
    },
    {
      title: `Heesen TRITON 50m`,
      buildDate: 2020,
      length: 55,
      cabins: 6,
      images: ['/img/yacht/favorites/yacht2.jpg'],
      price: '43 000 000 €',
      condition: `Новая`,
      alt: `Heesen TRITON 50m`,
    },
    {
      title: `Heesen 55M FDHF Pollux`,
      buildDate: 2020,
      length: 55,
      cabins: 6,
      images: [
        '/img/yacht/favorites/yacht3.jpg',
        '/img/yacht/favorites/yacht4.jpg',
        '/img/yacht/favorites/yacht5.jpg',
      ],
      price: '43 000 000 €',
      condition: `Новая`,
      alt: `Heesen 55M FDHF Pollux`,
    },
    {
      title: `Heesen Explorer Xventure 57m`,
      buildDate: 2020,
      length: 55,
      cabins: 6,
      images: [
        '/img/yacht/favorites/yacht4.jpg',
        '/img/yacht/favorites/yacht5.jpg',
        '/img/yacht/favorites/yacht6.jpg',
        '/img/yacht/favorites/yacht7.jpg',
      ],
      price: '43 000 000 €',
      condition: `Новая`,
      alt: `Heesen Explorer Xventure 57m`,
    },
    {
      title: `Heesen 50m Aquamarine`,
      buildDate: 2020,
      length: 55,
      cabins: 6,
      images: [
        '/img/yacht/favorites/yacht5.jpg',
        '/img/yacht/favorites/yacht6.jpg',
        '/img/yacht/favorites/yacht7.jpg',
        '/img/yacht/favorites/yacht8.jpg',
      ],
      price: '43 000 000 €',
      condition: `Новая`,
      alt: `Heesen 50m Aquamarine`,
    },
    {
      title: `Heesen Altea 50M`,
      buildDate: 2020,
      length: 55,
      cabins: 6,
      images: [
        '/img/yacht/favorites/yacht6.jpg',
        '/img/yacht/favorites/yacht7.jpg',
      ],
      price: '43 000 000 €',
      condition: `Новая`,
      alt: `Heesen Altea 50M`,
      badge: `Новинка`,
    },
    {
      title: `Heesen 55M FDHF Pollux`,
      buildDate: 2020,
      length: 55,
      cabins: 6,
      images: ['/img/yacht/favorites/yacht7.jpg'],
      price: '43 000 000 €',
      condition: `Новая`,
      alt: `Heesen 55M FDHF Pollux`,
    },
    {
      title: `Heesen 37M Li-Lien`,
      buildDate: 2020,
      length: 55,
      cabins: 6,
      images: ['/img/yacht/favorites/yacht8.jpg'],
      price: '43 000 000 €',
      condition: `Новая`,
      alt: `Heesen 37M Li-Lien`,
    },
  ],
}
