export const NewsMainData = {
  header: `Новости`,
  filters: [
    {
      type: 'checkbox',
      items: [
        'Abeking & Rasmussen',
        'AB Yachts',
        'Admiral Tecnomar',
        'Alloy Yachts',
        'Moonen',
        'Dominator',
        'Lurssen',
      ],
      title: 'Верфь',
      activeTitle: 'Верфи',
    },
    { type: 'toggle', title: 'Мега-яхты', quantity: 4 },
    { type: 'toggle', title: 'Новинки', quantity: 2 },
    { type: 'toggle', title: 'Эксклюзив', quantity: 5 },
    { type: 'toggle', title: 'Обзоры', quantity: 2 },
    {
      type: 'checkbox',
      items: [
        'Нидерланды',
        'Италия',
        'Великобритания',
        'Дания',
        'Канада',
        'Норвегия',
        'Швеция',
      ],
      title: 'Страны',
      activeTitle: 'Страны',
    },
    {
      type: 'checkbox',
      items: ['Моторная', 'Парусная', 'Экспедиционная', 'Траулер'],
      title: 'Тип яхты',
      activeTitle: 'Типы',
    },
  ],
  news: [
    {
      date: `15 апреля 2020`,
      title: `Гибкие условия бронирования морских путешествий летом 2020 г.`,
      text: `В связи со сложившейся в мире непростой обстановкой компания Arcon Yachts предлагает новые гибкие условия отмены договоров аренды яхт по всем направлениям без штрафов.`,
      src: `/img/news/newsPhoto1.jpg`,
      width: 373,
      height: 272,
    },
    {
      date: `15 апреля 2020`,
      title: `Международная выставка яхт в Каннах 2019`,
      text: `С 10 по 15 сентября 2019 года компания Arcon Yachts рада пригласить своих клиентов в Канны на крупнейшее ежегодное боат-шоу – «Cannes Yachting Festival». В этом году выставка проводится в  42-й раз, и в атмосфере праздника здесь соберутся ...`,
      src: `/img/news/newsPhoto2.jpg`,
      width: 373,
      height: 272,
    },
    {
      date: `15 апреля 2020`,
      title: `Новый проект ASTER 50м Heesen будет доставлен в Июне!`,
      text: `ARCON YACHTS рады сообщить, что многолетняя история сотрудничества компании и голландской верфи HEESEN пополнилась еще одним успешным проектом! `,
      src: `/img/news/newsPhoto3.jpg`,
      width: 373,
      height: 272,
    },
    {
      date: `15 апреля 2020`,
      title: `New construction 58M motor yacht Project Phi by Royal Huisman is signed`,
      text: `ARCON YACHTS с гордостью объявляет о строительстве нового уникального проекта Project Phi 58M вместе с голландской верфью Royal Huisman, а также в сотрудничестве с дизайнерским бюро Cor D. Rover ...`,
      src: `/img/news/newsPhoto4.jpg`,
      width: 373,
      height: 272,
    },
    {
      date: `15 апреля 2020`,
      title: `ТОП-5 Направлений для Чартера Яхты Зимой`,
      text: `Зимний яхтенный сезон – прекрасный способ вырваться на неделю-две в жаркое лето и освоить новые маршруты на моторной, парусной яхте или катамаране. `,
      src: `/img/news/newsPhoto5.jpg`,
      width: 373,
      height: 272,
    },
    {
      date: `15 апреля 2020`,
      title: `Клиентские дни VAN DER VALK 23-26 марта 2017`,
      text: `Arcon Yachts вновь рады пригласить Вас на ежегодное клиентское мероприятие верфи VAN DER VALK в г. Вальвейк (Нидерланды), где Вы сможете ознакомиться с последними разработками и увидеть своими глазами наши текущие проекты`,
      src: `/img/news/newsPhoto6.jpg`,
      width: 373,
      height: 272,
    },
  ],
  noveltyBlock: {
    title: `Новые яхты`,
    yachts: [
      {
        title: `Heesen 55M FDHF Pollux`,
        buildDate: 2020,
        length: 55,
        cabins: 6,
        images: ['/img/yachts-list/slide8.jpg'],
        price: '43 000 000 €',
        condition: `Новая`,
        alt: `Heesen 55M FDHF Pollux`,
        width: 490,
        height: 332,
      },
      {
        title: `Heesen 55M FDHF Pollux`,
        buildDate: 2020,
        length: 55,
        cabins: 6,
        images: ['/img/yachts-list/slide9.jpg'],
        price: '43 000 000 €',
        condition: `Новая`,
        alt: `Heesen 55M FDHF Pollux`,
        width: 490,
        height: 332,
      },
      {
        title: `Heesen 55M FDHF Pollux`,
        buildDate: 2020,
        length: 55,
        cabins: 6,
        images: ['/img/yachts-list/slide10.jpg'],
        price: '43 000 000 €',
        condition: `Новая`,
        alt: `Heesen 55M FDHF Pollux`,
        width: 490,
        height: 332,
      },
      {
        title: `Heesen 55M FDHF Pollux`,
        buildDate: 2020,
        length: 55,
        cabins: 6,
        images: ['/img/yachts-list/slide10.jpg'],
        price: '43 000 000 €',
        condition: `Новая`,
        alt: `Heesen 55M FDHF Pollux`,
        width: 490,
        height: 332,
      },
    ],
    mobButtonText: `Смотреть все`,
  },
  subscription: {
    title: `Подписывайтесь на нашу рассылку`,
    subtitle: `Будьте в курсе новостей яхтенного мира`,
    submitText: `Подписаться`,
  },
  infoBlock: {
    title: `Новости от${`\n`}ARCON YACHTS`,
    content: [
      `У нас вы сможете купить новые элитные яхты и подержанные суда, которые находятся в России, Казахстане, Украине и европейских странах. Наши специалисты выполнят всю сложную ответственную работу и оставят вам только приятные хлопоты.`,
      `Узнать цены на яхты и получить о них основную информацию Вы можете в нашем каталоге. В нем размещены фото и видео материалы, спецификации и планы палуб. Можно сравнить предлагаемые модели и купить яхту, которая идеально соответствует вашим требованиям. Чтобы быстро найти подходящие предложения, воспользуйтесь фильтром, где в качестве критериев поиска можно указать стоимость яхты, производителя, длину и прочие характеристики. Подробную информацию Вы можете запросить у наших консультантов. Консультанты расскажут о любых интересующих вас моделях, а также как и где купить яхту. Заявки на приобретение оформляются по телефону и в он-лайн режиме.`,
      `Arcon Yachts вновь рады пригласить Вас на ежегодное клиентское мероприятие верфи VAN DER VALK в г. Вальвейк (Нидерланды), где Вы сможете ознакомиться с последними разработками и увидеть своими глазами наши текущие проекты`,
      `В связи со сложившейся в мире непростой обстановкой компания Arcon Yachts предлагает новые гибкие условия отмены договоров аренды яхт по всем направлениям без штрафов.`,
    ],
    button: `Показать полностью`,
  },
}
