export const FormType = {
  interestedInCost: 'INTERESTED_IN_COST',
  needConsultation: 'NEED_CONSULTATION',
  interestedInExcursion: 'INTERESTED_IN_EXCURSION',
  needRent: 'NEED_RENTAL',
  specialConditions: 'SPECIAL_CONDITIONS',
  yachtSelection: 'YACHT_SELECTION',
  yachtBooking: 'BOOKING_FOR_RENT',
  yachtDelivery: 'NEED_DELIVERY',
  cruise: 'CRUISE',
  yachtSell: 'SELL_YACHT',
  yachtBuilding: 'CONSTRUCTION_APPLICATION',
  newsSubscription: 'SUBSCRIBE_NEWS',
  eventInvitation: 'EVENT_INVITATION',
  managementRequest: 'MANAGEMENT_REQUEST',
  registrationRequest: 'REGISTRATION_REQUEST',
  parkingRequest: 'PARKING_SPACE_REQUES',
}
